import { Platform, StyleSheet, StatusBar } from "react-native";
import colors from "./colors";

const styles = StyleSheet.create({
  containerSafe: {
    flex: 1,
    backgroundColor: colors.columbiaBlue,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  container: {
    flex: 1,
    backgroundColor: colors.columbiaBlue,
  },
  background: {
    flex: 1,
    backgroundColor: colors.columbiaBlue,
    alignItems: "center",
    justifyContent: "center",
    resizeMode: "contain",
  },
  background2: {
    flex: 1,
    resizeMode: "cover",
  },
  buttonRadius: {
    borderRadius: 7,
  },
  buttonPrimary: {
    borderRadius: 7,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.skobeloffBorder,
    backgroundColor: colors.skobeloff,
  },
  textPrimary: {
    bottom: 2,
    fontWeight: "bold",
    color: colors.columbiaBlue,
    paddingHorizontal: 4,
  },
  buttonSecondary: {
    borderRadius: 7,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.mountainMeadowBorder,
    backgroundColor: colors.mountainMeadow,
  },
  textSecondary: {
    bottom: 2,
    fontWeight: "bold",
    color: colors.indigoDye,
    paddingHorizontal: 4,
  },
  buttonEdit: {
    borderRadius: 7,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.carrotOrange,
    backgroundColor: colors.transparent,
  },
  textEdit: {
    bottom: 2,
    fontWeight: "bold",
    color: colors.carrotOrange,
    paddingHorizontal: 4,
  },
  buttonWarning: {
    borderRadius: 7,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.venetianRed,
    backgroundColor: colors.transparent,
  },
  textWarning: {
    bottom: 2,
    fontWeight: "bold",
    color: colors.venetianRed,
    paddingHorizontal: 4,
  },
  buttonCancel: {
    borderRadius: 7,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.venetianRedBorder,
    backgroundColor: colors.venetianRed,
  },
  textCancel: {
    bottom: 2,
    fontWeight: "bold",
    color: colors.lightRed,
    paddingHorizontal: 4,
  },
  title: {
    fontSize: 42,
    padding: 2,
    fontWeight: "bold",
    color: colors.skobeloff,
    backgroundColor: colors.columbiaBlueTransparent,
    borderRadius: 15,
  },
  input: {
    minWidth: "70%",
    maxWidth: "70%",
    height: 45,
    borderWidth: 1,
    borderTopRightRadius: 7,
    borderBottomRightRadius: 7,
    paddingHorizontal: 7,
    borderColor: colors.columbiaBlueBorder,
    backgroundColor: colors.columbiaBlue,
  },
  inputIcon: {
    borderTopLeftRadius: 7,
    borderBottomLeftRadius: 7,
    borderRightWidth: 0,
    borderColor: colors.columbiaBlueBorder,
    backgroundColor: colors.indigoDye,
    paddingHorizontal: 5,
    borderWidth: 1,
    height: 45,
    width: 45,
    alignItems: "center",
    justifyContent: "center",
  },
  separator: {
    borderBottomColor: colors.indigoDye,
    borderBottomWidth: 2,
    minWidth: "70%",
    paddingVertical: 4,
  },
  separator100: {
    borderBottomColor: colors.skobeloff,
    borderBottomWidth: 1,
    width: "100%",
    paddingVertical: 4,
  },
  lowerText: {
    color: colors.black,
    textAlign: "center",
    paddingHorizontal: 3,
  },
  lowerTextBackground: {
    backgroundColor: colors.columbiaBlueTransparent,
    borderRadius: 5,
    flexDirection: "row",
  },
  warning: {
    color: colors.red,
    textAlign: "center",
    padding: 3,
    backgroundColor: colors.redTransparent,
    borderRadius: 7,
  },
  flatList: {
    width: "100%",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },

  // antigos styles, seria uma melhor approach guardar os estilos únicos a um componente no próprio ficheiro e aqueles que
  // forem globais seriam inseridos aqui, evitando-se aglomeração de estilos

  mainContainer: {
    flex: 1,
    backgroundColor: "powderblue",
  },
  headerBG: {
    backgroundColor: "steelblue",
  },
  headerBold: {
    fontWeight: "bold",
  },
  container2: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "powderblue",
  },
  input_add: {
    textAlign: "center",
    fontSize: 16,
  },
  input_button_mine: {
    textAlign: "center",
    fontSize: 16,
    padding: 16,
    marginBottom: 10,
    width: 200,
    backgroundColor: "#00747A",
  },
  input_button_mine_v2: {
    fontSize: 16,
    padding: 8,
    marginBottom: 10,
    width: 120,
    backgroundColor: "#09BC8A",
  },
  input_large: {
    width: 250,
    height: 250,
    padding: 10,
    borderWidth: 1,
    borderColor: "black",
    marginBottom: 10,
  },
  layer2: {
    flex: 4,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "powderblue",
  },
  header: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 40,
    marginTop: 40,
  },
  postListItem: {
    width: "90%",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    margin: 14,
    padding: 10,
    backgroundColor: "#fff",
  },
  postTitle: {
    fontWeight: "bold",
    fontSize: 18,
    marginBottom: 10,
  },
  postSeparator: {
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    marginTop: 8,
    marginBottom: 8,
  },
  postSeparatorLg: {
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    marginTop: 40,
    marginBottom: 8,
  },
  postButton: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  postButton2x: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  button: {
    marginTop: 20,
    marginBottom: 20,
  },
  button2: {
    alignItems: "center",
    backgroundColor: "#DDDDDD",
    padding: 10,
    marginBottom: 10,
    marginTop: 10,
  },
  input2: {
    width: "90%",
    height: 44,
    padding: 10,
    borderWidth: 1,
    borderColor: "black",
    marginBottom: 10,
  },
  input_large2: {
    minWidth: "70%",
    height: 250,
    borderWidth: 1,
    padding: 10,
    borderRadius: 7,
    marginBottom: 10,
    paddingHorizontal: 7,
    borderColor: colors.columbiaBlueBorder,
    backgroundColor: colors.columbiaBlue,
  },
  imagem_avatar: {
    alignItems: "center",
    flex: 1,
    width: 200,
    height: 200,
    padding: 10,
    marginBottom: 10,
    resizeMode: "contain",
    borderRadius: 100,
  },
  imagem_home: {
    alignItems: "center",
    width: "100%",
    height: 250,
    padding: 10,
    marginBottom: 10,
    resizeMode: "cover",
  },
  imagem_categoria: {
    alignItems: "center",
    flex: 1,
    width: 100,
    height: 100,
    padding: 10,
    marginBottom: 10,
    resizeMode: "contain",
  },
  imagem_icon: {
    height: 75,
    width: 75,
    borderRadius: 100,
    flex: 1,
    resizeMode: "contain",
  },
  inputAndroid: {
    fontSize: 14,
    width: "90%",
    height: 44,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "blue",
    borderRadius: 8,
    color: "black",
    paddingRight: 30, // to ensure the text is never behind the icon
  },
  img: {
    width: 262,
    height: 48,
  },
  container2: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-around",
  },
  main: {
    flex: 1,
    flexDirection: "column",
    marginTop: 50,
  },
  layerTop: {
    padding: 6,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  customButtonEditText: {
    color: "#935116",
    fontSize: 14,
    textTransform: "uppercase",
  },
  customButtonCancel: {
    marginTop: 10,
    marginBottom: 10,
    alignItems: "center",
    backgroundColor: "#C0392B",
    borderRadius: 7,
  },
  customButton: {
    marginTop: 10,
    marginBottom: 30,
    alignItems: "center",
    backgroundColor: "#1E8449",
    borderRadius: 3,
  },
  customButtonText: {
    textAlign: "center",
    padding: 10,
    color: "#EAFAF1",
    textTransform: "uppercase",
  },
  layer1: {
    flex: 4,
    alignItems: "center",
    padding: 20,
  },
  layer3: {
    flex: 1,
    flexDirection: "row",
  },
  layer4: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#21618C",
  },
  layer5: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "steelblue",
  },
});

export default styles;
